global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: 'nomad_metrics'
    scheme: 'https'
    tls_config:
        insecure_skip_verify: true
    consul_sd_configs:
    - server: '{{ env "NOMAD_IP_prometheus_ui" }}:8500'
      services: ['nomad-client']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex: '(.*)http(.*)'
      action: keep

    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']

  - job_name: 'consul_metrics'
    scheme: 'http'
    consul_sd_configs:
    - server: '{{ env "NOMAD_IP_prometheus_ui" }}:8500'
      services:
        - 'consul'

    scrape_interval: 5s
    metrics_path: /v1/agent/metrics
    params:
      format: ['prometheus']

    relabel_configs:
    - source_labels: [__address__]
      regex: ^(.*):(.*)$
      target_label: __address__
      replacement: ${1}:8500

    - source_labels: [__meta_consul_node]
      regex: (.*)
      target_label: host
      replacement: ${1}

# https://www.robustperception.io/extracting-labels-from-legacy-metric-names
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: '(consul_memberlist_tcp)_(.*)'
      replacement: '${2}'
      target_label: type
    - source_labels: [__name__]
      regex: '(consul_memberlist_tcp)_(.*)'
      replacement: '${1}_count'
      target_label: __name__

    - source_labels: [__name__]
      regex: '(consul_memberlist_udp)_(.*)'
      replacement: '${2}'
      target_label: type
    - source_labels: [__name__]
      regex: '(consul_memberlist_udp)_(.*)'
      replacement: '${1}_count'
      target_label: __name__

    - source_labels: [__name__]
      regex: '(consul_raft_replication_heartbeat)_(.+)(_\w?)?'
      replacement: '${2}'
      target_label: query
    - source_labels: [__name__]
      regex: '(consul_raft_replication_heartbeat)_(.+)(_\w?)?'
      replacement: '${1}${3}'
      target_label: __name__

    - source_labels: [__name__]
      regex: '(consul_raft_replication_appendEntries_rpc)_(.+)(_\w?)?'
      replacement: '${2}'
      target_label: query
    - source_labels: [__name__]
      regex: '(consul_raft_replication_appendEntries_rpc)_(.+)(_\w?)?'
      replacement: '${1}${3}'
      target_label: __name__

  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'vault'
    metrics_path: "/v1/sys/metrics"
    scheme: "https"
    tls_config:
        insecure_skip_verify: true
    params:
      format: ['prometheus']
    bearer_token: {{ env "VAULT_TOKEN" }}
    static_configs:
    - targets: ['active.vault.service.consul:8200']

    # https://www.robustperception.io/extracting-labels-from-legacy-metric-names
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: '(vault_route)_(\w[^_]+)_(\w+)_count'
      replacement: '${2}'
      target_label: method
    - source_labels: [__name__]
      regex: '(vault_route)_(\w[^_]+)_(\w+)_count'
      replacement: '${3}'
      target_label: path
    - source_labels: [__name__]
      regex: '(vault_route)_(\w[^_]+)_(\w+)_count'
      replacement: '${1}_count'
      target_label: __name__